POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "New Event 5",
    "details": "...",
    "maximumAttendees": 5
}

###

POST http://localhost:3333/events/5877937d-19b1-46e4-8bd5-ce22d04260f6/attendees
Content-Type: application/json

{
    "name": "Alexandre Lima",
    "email": "alexandre4@gmail.com"
}

###

GET http://localhost:3333/events/5877937d-19b1-46e4-8bd5-ce22d04260f6

###
GET http://localhost:3333/attendees/1/badge

###
GET http://localhost:3333/attendees/1/check-in