POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "New Event 6",
    "details": "...",
    "maximumAttendees": 50
}

###

POST http://localhost:3333/events/a9aeb307-b292-4d87-9fe6-0808366eaf45/attendees
Content-Type: application/json

{
    "name": "Diego Lima",
    "email": "diego@gmail.com"
}

###

GET http://localhost:3333/events/a9aeb307-b292-4d87-9fe6-0808366eaf45

###
GET http://localhost:3333/attendees/6/badge

###
GET http://localhost:3333/attendees/6/check-in

###

GET http://localhost:3333/events/a9aeb307-b292-4d87-9fe6-0808366eaf45/attendees?query=alexandre